stages:
  - deploy

variables:
  KUBECONFIG: "/builds/$CI_PROJECT_PATH/kubeconfig"

deploy-backend:
  stage: deploy
  image: bitnami/kubectl:1.29
  script:
    - echo "$KUBE_CONFIG_DATA" | base64 -d > $KUBECONFIG
    - kubectl apply -f backend-deployment.yaml
  only:
    - main
