stages:
  - deploy

deploy:
  image: alpine/k8s:1.29.15
  tags:
    - k8s
    - local
  stage: deploy
  before_script:
    - echo "$KUBECONFIG" > kubeconfig
    - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
  script:
    - kubectl version --client
    - kubectl apply -f backend-deployment.yaml
    - kubectl apply -f frontend-deployment.yaml
  after_script:
    - echo "Deployed frontend..."
    - echo "Deployed backend..."
  only:
    - main


