stages:
  - deploy

variables:
  KUBECONFIG: "/builds/$CI_PROJECT_PATH/kubeconfig"

deploy-frontend:
  stage: deploy
  image: alpine/k8s:1.29.15
  script:
    - echo "$KUBE_CONFIG_DATA" | base64 -d > $KUBECONFIG
    - kubectl apply -f frontend-deployment.yaml
  only:
    - main

deploy-backend:
  stage: deploy
  image: nginx/kubectl:latest
  script:
    - echo "$KUBE_CONFIG_DATA" | base64 -d > $KUBECONFIG
    - kubectl apply -f backend-deployment.yaml
  only:
    - main
