stages:
  - deploy

deploy_to_kubernetes:
  image: alpine/k8s:1.27.4
  tags:
    - k8
  stage: deploy
  before_script:
    - echo "$KUBECONFIG" > kubeconfig
    - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
  script:
    - kubectl version --client
    - kubectl apply -f backend-deployment.yaml
    - kubectl apply -f frontend-deployment.yaml
  only:
    - main
