stages:
  - deploy

deploy:
  image: alpine/k8s:1.29.15
  tags:
    - k8s
    - local
  stage: deploy
  before_script:
  - mkdir -p ~/.kube
  - echo "$KUBECONFIG_DATA" | base64 -d > ~/.kube/config
  script:
    - kubectl apply -f postgres-deployment.yaml
    - kubectl apply -f postgres-service.yaml
    - kubectl apply -f backend-deployment.yaml
    - kubectl apply -f backend-service.yaml
    - kubectl apply -f frontend-deployment.yaml
    - kubectl apply -f frontend-service.yaml
    - kubectl apply -f pgadmin-deployment.yaml
    - kubectl apply -f pgadmin-service.yaml
  after_script:
    - echo "Deployed postgres..."
    - echo "Deployed backend..."
    - echo "Deployed frontend..."
    - echo "Deployed pgadmin..."
  only:
    - main


    