apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  labels:
    app: flask-backend
spec:
  type: NodePort
  selector:
    app: flask-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500