apiVersion: apps/v1
kind: Deployment
metadata:
  name: barista-backend
  labels:
    app: barista-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista-backend
  template:
    metadata:
      labels:
        app: barista-backend
    spec:
      containers:
        - name: barista-backend
          image: 95337/barista-backend:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: barista-backend-service
spec:
  selector:
    app: barista-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
