apiVersion: apps/v1
kind: Deployment
metadata:
  name: barista-backend
  labels:
    app: barista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista
  template:
    metadata:
      labels:
        app: barista
    spec:
      containers:
        - name: barista-cafe
          image: 95337/barista-backend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: barista-backend-service
spec:
  selector:
    app: barista
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
