apiVersion: v1
kind: Service
metadata:
  name: barista-frontend
spec:
  type: NodePort
  selector:
    app: barista-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30587