apiVersion: apps/v1
kind: Deployment
metadata:
  name: barista-frontend
  labels:
    app: barista
spec:
  replicas: 2
  selector:
    matchLabels:
      app: barista
  template:
    metadata:
      labels:
        app: barista
    spec:
      containers:
        - name: barista-cafe
          image: 95337/barista_cafe:v3
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: barista-frontend-service
spec:
  selector:
    app: barista
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Change to LoadBalancer if using a cloud provider
