apiVersion: apps/v1
kind: Deployment
metadata:
  name: barista-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista-frontend
  template:
    metadata:
      labels:
        app: barista-frontend
    spec:
      containers:
        - name: barista-frontend
          image: 95337/barista_cafe:v1
          ports:
            - containerPort: 80