apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
spec:
  ports:
    - port: 9187
      targetPort: 9187
      nodePort: 30087
      protocol: TCP
  selector:
    app: postgres-exporter
  type: NodePort