stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "Starting CI..."

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - echo "Run your tests here (optional)"

deploy:
  stage: deploy
  script:
    - docker-compose up -d
  only:
    - main
